module.exports = {
  location: [
    'live in','living in','based in','located in','moved to','moving to','hometown',
    'my city','my country','my state','my town','my address','my location',
    'city','country','state','province','county','region','district','town','village','suburb',
    'street','avenue','road','zip code','postal code',
    'timezone','local time','downtown','near me','neighborhood',
    'coordinates','latitude','longitude','gps location',
    'at the airport','border crossing','commute to',
    'united states','united kingdom','canada','australia','new zealand',
    'new york','los angeles','chicago','houston','seattle','miami','denver',
    'london','paris','berlin','amsterdam','madrid','rome','tokyo','sydney','toronto','dubai',
    'east coast','west coast','midwest','south america','middle east','southeast asia',
    'my apartment','my house','my flat','my place','my home','i rent','i own',
    'just got home','leaving my','on my way home','heading home',
    'my building','my complex','my floor','my unit',
    'grew up in','raised in','was born in','from the',
    'local here','moved here','new to the area',
    'my school is in','my job is in','my campus',
    'nearest city','closest city','an hour from','minutes from downtown',
    'central time','eastern time','pacific time','mountain time','gmt','bst','cest','aest',
  ],
  economics: [
    'my salary','my wage','my income','my paycheck','my earnings','hourly rate','annual salary',
    'my job','i work at','i work for','i work in','employed at','got hired','got fired','laid off','quit my job','lost my job',
    'i make ','i earn ','making money','side hustle','passive income',
    'money','cash flow','dollar','euro','pound','bitcoin','crypto','my wallet',
    'bank account','loan','in debt','mortgage','rent is','pay bills','credit card',
    'invest','stocks','trading','my portfolio','net worth',
    'my budget','savings','broke',"can't afford",'afford to','living paycheck',
    'freelance','my client','my business','my startup','my company',
    'tax return','write off','self employed',
    'my venmo','my cashapp','my paypal','my zelle','send me money','pay me back',
    'my debit','my checking account','my savings account','my routing number',
    'i owe','you owe me','split the bill','going dutch',
    'got a raise','pay cut','bonus','commission','overtime pay',
    'onlyfans','patreon','ko-fi','gumroad','my store','my shop',
    'i sell','reselling','dropshipping','affiliate','referral code',
    'gambling','sports betting','my bookie','won money','lost money',
    'i just bought','just purchased','spending money on',
  ],
  identity: [
    'my name is','real name','irl name','call me','known as','people call me',
    'my birthday','born in','birth date','turning ','years old',"i'm ",'i am ',
    'my pronouns','he/him','she/her','they/them','non-binary','trans ',
    'my email','my gmail','my yahoo','my phone','my number','my cell',
    'my full name','my first name','my last name','my middle name','maiden name',
    'my passport','my license','my id','my ssn','my social security',
    'my username','my handle','my account name','my alias',
    'my alt','my main account','my second account','my backup account',
    'my real account','my other discord','my other account',
    'photo of me','picture of me','selfie','my face','my pfp is me',
    'thats me in','thats my','that was me','my old username','used to go by',
    'they know me as','irl i go by','offline i am',
    'my dob','date of birth','born on','i was born','i turn',
    'my blood type','my height','my weight',
    'my nationality','my ethnicity','my heritage','my race',
    'i am autistic','i have adhd','my diagnosis','my condition','my disability',
  ],
  social: [
    'my twitter','my instagram','my facebook','my tiktok','my youtube','my twitch',
    'my reddit','my github','my linkedin','my snapchat','my telegram','my discord',
    'follow me on','my profile','my channel','my page','my account',
    'my girlfriend','my boyfriend','my partner','my spouse','my wife','my husband',
    'we are married',"i'm single","i'm dating",'in a relationship',
    'my brother','my sister','my mom','my dad','my mother','my father',
    'my parents','my family','my sibling','my kids','my children',
    'my best friend','my friend','my roommate','my coworker','my colleague',
    'my ex','my crush',
    'my steam','my psn','my xbox gamertag','my riot id','my battlenet',
    'my pinterest','my tumblr','my mastodon','my bluesky','my threads',
    'link in bio','my linktree','my carrd','find me at','add me on',
    'my close friends','my gc','my group chat','my server',
    'met online','met irl','we met on','they dm me','i dm them',
    'my toxic ex','abusive relationship','went no contact',
    "my neighbor's","nextdoor neighbor",'guy next door','girl next door',
    'my landlord','my boss','my manager','my coworker named',
    'my therapist','my doctor','my lawyer',
    'my dealer','my plug','my connect',
  ],
  activities: [
    'hit the gym','my workout','i exercise','going running','my training',
    'i game','i play','my stream','i stream','i watch','i read',
    'at school','my university','my college','in class','i study','doing homework','my professor',
    'i code','i program','i dev','i hack','my project',
    'work from home','wfh','remote work','in the office','on my commute',
    'i travel','on vacation','on a trip','my flight','road trip',
    'i woke up','going to sleep','my morning','my daily','every day',
    'went to the gym','at the restaurant','at the bar','at the party',
    'cooking','i baked','eating','drinking','night out',
    'my routine','wake up at','go to bed at','my schedule','my shift',
    'my church','my mosque','my temple','i pray','my religion','i believe in',
    'my car','i drive','my license plate','my parking','my garage',
    'picked up','dropped off','my uber','my lyft','taking the bus','taking the train',
    'just landed','just arrived','checked in','at the hotel','at the airbnb',
    'at the mall','at walmart','at target','grocery store','at the pharmacy',
    'at the hospital','urgent care','er visit','surgery','my prescription',
    'i smoke','i vape','i drink','i use','i take','my meds',
    'my pet','my dog','my cat','my fish','walking my dog',
    'at the park','at the beach','at the lake','camping','hiking trail',
    'my concert','my event','my show','bought tickets for',
  ],
  technical: [
    'my pc','my computer','my laptop','my macbook','running windows','running linux',
    'my android','my iphone','my phone','my tablet','my ipad',
    'my browser','using chrome','using firefox','my vpn',
    'my ip','my server','my hosting','my domain','my website','my vps',
    'my gpu','my cpu','my ram','my setup','my rig','my specs','my build',
    'my wifi','my router','my internet','my ethernet',
    'dual boot','my distro','my os','running arch','running ubuntu','running debian',
    'my terminal','my shell','bash','zsh','powershell',
    'my api key','my token','my secret','my password','my credentials',
    'leaked my','doxxed','my ip got','someone found my','exposed my',
    'my minecraft','my roblox','my valorant','my csgo','my fortnite',
    'my repo','my commit','my pull request','my deploy','my prod',
    'my aws','my gcp','my azure','my cloudflare','my nginx',
    'port forwarding','opened a port','my public ip','static ip',
    'my 2fa','my auth app','lost access to','locked out of',
    'my ssh key','my private key','my config file',
  ],
  criminal: [
    'i got arrested','got a warrant','on probation','on parole','my charges','felony','misdemeanor',
    'i got charged with','court date','my lawyer','my public defender','bail money',
    'restraining order','i violated','community service','ankle monitor',
    'i did time','i was locked up','juvie','county jail','state prison',
    'i sell drugs','i deal','trap house','my re-up','fronted me',
    'i carry','my gun','my piece','my strap','my 9','my 40','my glock',
    'i was jumped','got robbed','robbed someone','jumped someone',
    'my gang','my set','my block','running with','affiliated with',
    'i got shot','got stabbed','shot someone','drive-by',
    'i stole','shoplifting','boosting','five finger discount',
    'my warrant','bench warrant','failure to appear','skipped bail',
    'i scam','i phish','i fraud','fake id','fake card','cloned cards',
    'hit a lick','stick-up','my victim','my target',
    'i hack','i rat','i ddos','botnet','i carded',
  ],
  physical: [
    'my height is','i am tall','i am short','my weight','i weigh',
    'my tattoo','my ink','my piercing','my scar','my birthmark',
    'i have blue eyes','i have brown eyes','my hair is','i dyed my hair',
    'i shaved','i cut my hair','my beard','my mustache',
    'my skin','i have acne','my complexion',
    'my disability','i use a wheelchair','i walk with a cane','visually impaired',
    'my surgery','recovering from','just got out of the hospital',
    'my glasses','my contacts','i wear glasses',
    'my dental','my braces','my retainer',
    'my build','i bulk','i cut','body fat','body dysmorphia',
  ],
  credentials: [
    'my password is','default password','reset my password','forgot my password',
    'my email is','email address','login email','account email',
    'my username is','log in with','sign in with','i use the same password',
    'my api key','my token is','my secret key','auth token','bearer token',
    'my 2fa code','backup codes','recovery code','lost my authenticator',
    'my pin is','my pin number','4 digit','6 digit code',
    'security question','my mothers maiden','my pets name','my first school',
    'i reuse','same password everywhere','bad with passwords','no 2fa',
    'my seed phrase','my recovery phrase','private key','wallet passphrase',
  ],
  places: [
    // ── countries ──────────────────────────────────────────────────────────
    // africa
    'algeria','angola','benin','botswana','burkina faso','burundi','cabo verde','cameroon',
    'central african republic','chad','comoros','congo','dr congo','djibouti','egypt',
    'equatorial guinea','eritrea','eswatini','ethiopia','gabon','gambia','ghana','guinea',
    'guinea-bissau','ivory coast','kenya','lesotho','liberia','libya','madagascar','malawi',
    'mali','mauritania','mauritius','morocco','mozambique','namibia','niger','nigeria',
    'rwanda','senegal','seychelles','sierra leone','somalia','south africa','south sudan',
    'sudan','tanzania','togo','tunisia','uganda','zambia','zimbabwe',
    // americas
    'argentina','bahamas','barbados','belize','bolivia','brazil','canada','chile',
    'colombia','costa rica','cuba','dominica','dominican republic','ecuador','el salvador',
    'grenada','guatemala','guyana','haiti','honduras','jamaica','mexico','nicaragua',
    'panama','paraguay','peru','suriname','trinidad and tobago','united states','uruguay',
    'venezuela',
    // asia
    'afghanistan','armenia','azerbaijan','bahrain','bangladesh','bhutan','brunei',
    'cambodia','china','cyprus','georgia','india','indonesia','iran','iraq','israel',
    'japan','jordan','kazakhstan','kuwait','kyrgyzstan','laos','lebanon','malaysia',
    'maldives','mongolia','myanmar','nepal','north korea','oman','pakistan','palestine',
    'philippines','qatar','saudi arabia','singapore','south korea','sri lanka','syria',
    'taiwan','tajikistan','thailand','timor-leste','turkey','turkmenistan',
    'united arab emirates','uzbekistan','vietnam','yemen',
    // europe
    'albania','andorra','austria','belarus','belgium','bosnia','bulgaria','croatia',
    'czech republic','denmark','estonia','finland','france','germany','greece','hungary',
    'iceland','ireland','italy','kosovo','latvia','liechtenstein','lithuania','luxembourg',
    'malta','moldova','monaco','montenegro','netherlands','north macedonia','norway',
    'poland','portugal','romania','russia','san marino','serbia','slovakia','slovenia',
    'spain','sweden','switzerland','ukraine','united kingdom','england','scotland','wales',
    // oceania
    'australia','fiji','kiribati','marshall islands','micronesia','nauru','new zealand',
    'palau','papua new guinea','samoa','solomon islands','tonga','tuvalu','vanuatu',

    // ── us states ──────────────────────────────────────────────────────────
    'alabama','alaska','arizona','arkansas','california','colorado','connecticut',
    'delaware','florida','georgia','hawaii','idaho','illinois','indiana','iowa',
    'kansas','kentucky','louisiana','maine','maryland','massachusetts','michigan',
    'minnesota','mississippi','missouri','montana','nebraska','nevada','new hampshire',
    'new jersey','new mexico','new york','north carolina','north dakota','ohio',
    'oklahoma','oregon','pennsylvania','rhode island','south carolina','south dakota',
    'tennessee','texas','utah','vermont','virginia','washington','west virginia',
    'wisconsin','wyoming','washington dc',

    // ── canadian provinces ─────────────────────────────────────────────────
    'ontario','quebec','british columbia','alberta','manitoba','saskatchewan',
    'nova scotia','new brunswick','newfoundland','prince edward island',

    // ── us cities ──────────────────────────────────────────────────────────
    'new york','los angeles','chicago','houston','phoenix','philadelphia','san antonio',
    'san diego','dallas','san jose','austin','jacksonville','fort worth','columbus',
    'charlotte','indianapolis','san francisco','seattle','denver','nashville',
    'oklahoma city','el paso','las vegas','louisville','baltimore','milwaukee',
    'albuquerque','tucson','fresno','sacramento','kansas city','atlanta','omaha',
    'colorado springs','raleigh','long beach','minneapolis','tampa','new orleans',
    'arlington','honolulu','anaheim','santa ana','corpus christi','riverside',
    'st. louis','portland','pittsburgh','stockton','anchorage','cincinnati',
    'henderson','greensboro','plano','newark','toledo','orlando','jersey city',
    'laredo','madison','durham','lubbock','winston-salem','garland','scottsdale',
    'norfolk','chandler','reno','detroit','baton rouge','hialeah','chesapeake',
    'fremont','gilbert','birmingham','rochester','richmond','spokane','des moines',
    'memphis','buffalo','boise','huntsville','grand rapids','fontana','glendale',
    'salt lake city','sioux falls','fargo','little rock','mobile','shreveport',
    'tacoma','knoxville','oxnard','overland park','augusta','huntington beach',
    'worcester','fort lauderdale','brownsville','providence','garden grove',
    'oceanside','chattanooga','fort wayne','tempe','peoria','cape coral','eugene',
    'cary','springfield','corona','jackson','elk grove','clarksville','paterson',

    // ── canadian cities ────────────────────────────────────────────────────
    'toronto','montreal','vancouver','calgary','edmonton','ottawa','winnipeg',
    'quebec city','hamilton','kitchener','london','victoria','halifax','oshawa',
    'windsor','saskatoon','regina','sherbrooke','kelowna','barrie','abbotsford',
    'sudbury','kingston','saguenay','trois-rivières','burnaby','surrey','mississauga',

    // ── mexican cities ─────────────────────────────────────────────────────
    'mexico city','guadalajara','monterrey','puebla','tijuana','león','juárez',
    'mérida','san luis potosí','aguascalientes','hermosillo','saltillo','culiacán',
    'chihuahua','querétaro','morelia','cancún','veracruz','acapulco','oaxaca',
    'mexicali','san nicolás','ecatepec','naucalpan','zapopan',

    // ── south american cities ──────────────────────────────────────────────
    'são paulo','buenos aires','rio de janeiro','lima','bogotá','santiago','caracas',
    'quito','la paz','montevideo','asunción','guayaquil','cali','medellín','fortaleza',
    'belo horizonte','manaus','curitiba','recife','porto alegre','brasília','belém',
    'salvador','goiânia','córdoba','rosario','mendoza','barranquilla','cartagena',
    'cúcuta','bucaramanga','arequipa','trujillo','maracaibo','valencia','maracay',
    'ciudad guayana','barquisimeto','santa cruz','cochabamba','sucre',

    // ── european cities ────────────────────────────────────────────────────
    'london','paris','berlin','madrid','rome','barcelona','vienna','warsaw','budapest',
    'bucharest','hamburg','munich','milan','prague','sofia','brussels','athens',
    'amsterdam','stockholm','copenhagen','zurich','helsinki','oslo','lisbon','dublin',
    'lyon','marseille','frankfurt','stuttgart','düsseldorf','dortmund','essen',
    'leipzig','bremen','dresden','hanover','nuremberg','cologne','rotterdam',
    'the hague','utrecht','antwerp','ghent','bruges','geneva','basel','bern',
    'lausanne','krakow','lodz','wroclaw','poznan','gdansk','naples','turin',
    'palermo','genoa','bologna','florence','venice','catania','verona','seville',
    'valencia','zaragoza','bilbao','malaga','porto','thessaloniki','tallinn','riga',
    'vilnius','minsk','kyiv','kharkiv','odessa','lviv','belgrade','zagreb',
    'sarajevo','skopje','chisinau','bratislava','ljubljana','tirana','pristina',
    'podgorica','reykjavik','st petersburg','moscow','novosibirsk','yekaterinburg',
    'nizhny novgorod','kazan','chelyabinsk','omsk','samara','rostov','ufa',
    'krasnoyarsk','perm','volgograd','voronezh','saint petersburg',
    'manchester','birmingham uk','glasgow','liverpool','leeds','sheffield',
    'edinburgh','bristol','leicester','coventry','bradford','cardiff','belfast',

    // ── middle east & central asia cities ─────────────────────────────────
    'istanbul','ankara','izmir','bursa','riyadh','jeddah','mecca','medina','doha',
    'kuwait city','abu dhabi','dubai','muscat','amman','beirut','damascus','aleppo',
    'tel aviv','jerusalem','haifa','baku','tbilisi','yerevan','tashkent','almaty',
    'bishkek','dushanbe','ashgabat','nur-sultan','astana','islamabad','peshawar',
    'rawalpindi','faisalabad','multan','lahore','karachi','kabul','tehran','baghdad',
    'mosul','basra','nicosia','sana\'a',

    // ── asian cities ───────────────────────────────────────────────────────
    'tokyo','osaka','nagoya','sapporo','fukuoka','kyoto','kobe','yokohama','hiroshima',
    'sendai','beijing','shanghai','guangzhou','shenzhen','chongqing','tianjin',
    'wuhan','chengdu','nanjing','hangzhou','xian','dongguan','foshan','shenyang',
    'harbin','dalian','qingdao','zhengzhou','jinan','changsha','kunming','fuzhou',
    'seoul','busan','incheon','daegu','daejeon','gwangju',
    'mumbai','delhi','bangalore','hyderabad','ahmedabad','chennai','kolkata','surat',
    'pune','jaipur','lucknow','kanpur','nagpur','indore','thane','bhopal','visakhapatnam',
    'patna','vadodara','ghaziabad','ludhiana','agra','nashik','faridabad','meerut',
    'dhaka','chittagong','khulna','rajshahi','colombo','kathmandu','yangon','mandalay',
    'naypyidaw','bangkok','chiang mai','pattaya','phuket','ho chi minh city','hanoi',
    'da nang','hai phong','phnom penh','vientiane','singapore','kuala lumpur','penang',
    'johor bahru','taipei','taichung','kaohsiung','pyongyang','ulaanbaatar',
    'jakarta','surabaya','bandung','medan','semarang','palembang','makassar',
    'manila','quezon city','caloocan','davao','cebu','zamboanga',

    // ── african cities ─────────────────────────────────────────────────────
    'cairo','lagos','kinshasa','luanda','nairobi','dar es salaam','addis ababa',
    'khartoum','accra','casablanca','abidjan','alexandria','kano','cape town',
    'johannesburg','dakar','algiers','tunis','kampala','douala','yaoundé','lusaka',
    'harare','bamako','conakry','ouagadougou','antananarivo','maputo','lomé',
    'kaduna','ibadan','enugu','port harcourt','durban','pretoria','soweto',
    'kumasi','mombasa','zanzibar','mogadishu','asmara','djibouti city','juba',
    'kigali','bujumbura','windhoek','gaborone','maseru','mbabane','lilongwe',
    'blantyre','bangui','libreville','brazzaville','malabo','freetown','monrovia',
    'abuja','cotonou','niamey','ndjamena','bangui','lome','ouagadougou',

    // ── oceania cities ─────────────────────────────────────────────────────
    'sydney','melbourne','brisbane','perth','adelaide','gold coast','canberra',
    'newcastle','wollongong','hobart','darwin','townsville','cairns',
    'auckland','wellington','christchurch','hamilton','tauranga','dunedin',
    'port moresby','suva','honiara','port vila','nuku\'alofa','apia','funafuti',

    // ── regions & areas ────────────────────────────────────────────────────
    'the bronx','brooklyn','queens','manhattan','staten island',
    'silicon valley','bay area','socal','norcal','the south','the midwest',
    'new england','appalachia','the rust belt','the bible belt','the deep south',
    'the pacific northwest','the great plains','the sunbelt',
    'sub-saharan africa','north africa','west africa','east africa','southern africa',
    'the balkans','the caucasus','the levant','the gulf','the maghreb',
    'southeast asia','south asia','central asia','east asia','far east',
    'scandinavia','iberian peninsula','the balkans','eastern europe','western europe',
    'latin america','central america','the caribbean','south america','north america',
    'the middle east','the arctic','the amazon',
  ],
};
