module.exports = {
  location: [
    'live in','living in','based in','located in','moved to','moving to','hometown',
    'my city','my country','my state','my town','my address','my location',
    'city','country','state','province','county','region','district','town','village','suburb',
    'street','avenue','road','zip code','postal code',
    'timezone','local time','downtown','near me','neighborhood',
    'coordinates','latitude','longitude','gps location',
    'at the airport','border crossing','commute to',
    'united states','united kingdom','canada','australia','new zealand',
    'new york','los angeles','chicago','houston','seattle','miami','denver',
    'london','paris','berlin','amsterdam','madrid','rome','tokyo','sydney','toronto','dubai',
    'east coast','west coast','midwest','south america','middle east','southeast asia',
  ],
  economics: [
    'my salary','my wage','my income','my paycheck','my earnings','hourly rate','annual salary',
    'my job','i work at','i work for','i work in','employed at','got hired','got fired','laid off','quit my job','lost my job',
    'i make ','i earn ','making money','side hustle','passive income',
    'money','cash flow','dollar','euro','pound','bitcoin','crypto','my wallet',
    'bank account','loan','in debt','mortgage','rent is','pay bills','credit card',
    'invest','stocks','trading','my portfolio','net worth',
    'my budget','savings','broke',"can't afford",'afford to','living paycheck',
    'freelance','my client','my business','my startup','my company',
    'tax return','write off','self employed',
  ],
  identity: [
    'my name is','real name','irl name','call me','known as','people call me',
    'my birthday','born in','birth date','turning ','years old',"i'm ",'i am ',
    'my pronouns','he/him','she/her','they/them','non-binary','trans ',
    'my email','my gmail','my yahoo','my phone','my number','my cell',
    'my full name','my first name','my last name','my middle name','maiden name',
    'my passport','my license','my id','my ssn','my social security',
    'my username','my handle','my account name','my alias',
  ],
  social: [
    'my twitter','my instagram','my facebook','my tiktok','my youtube','my twitch',
    'my reddit','my github','my linkedin','my snapchat','my telegram','my discord',
    'follow me on','my profile','my channel','my page','my account',
    'my girlfriend','my boyfriend','my partner','my spouse','my wife','my husband',
    'we are married',"i'm single","i'm dating",'in a relationship',
    'my brother','my sister','my mom','my dad','my mother','my father',
    'my parents','my family','my sibling','my kids','my children',
    'my best friend','my friend','my roommate','my coworker','my colleague',
    'my ex','my crush',
  ],
  activities: [
    'hit the gym','my workout','i exercise','going running','my training',
    'i game','i play','my stream','i stream','i watch','i read',
    'at school','my university','my college','in class','i study','doing homework','my professor',
    'i code','i program','i dev','i hack','my project',
    'work from home','wfh','remote work','in the office','on my commute',
    'i travel','on vacation','on a trip','my flight','road trip',
    'i woke up','going to sleep','my morning','my daily','every day',
    'went to the gym','at the restaurant','at the bar','at the party',
    'cooking','i baked','eating','drinking','night out',
  ],
  technical: [
    'my pc','my computer','my laptop','my macbook','running windows','running linux',
    'my android','my iphone','my phone','my tablet','my ipad',
    'my browser','using chrome','using firefox','my vpn',
    'my ip','my server','my hosting','my domain','my website','my vps',
    'my gpu','my cpu','my ram','my setup','my rig','my specs','my build',
    'my wifi','my router','my internet','my ethernet',
    'dual boot','my distro','my os','running arch','running ubuntu','running debian',
    'my terminal','my shell','bash','zsh','powershell',
  ],
};
